#!/usr/bin/env python3
import sys # sys interacts with the Python interpreter
import os  # while os interacts with the operating system

# Add the current directory to the Python path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

# Import the main function from the package
from a_series_of_tubes.main import main

# Run the main function
if __name__ == '__main__':

    # Exit with the return code of the main function
    sys.exit(main())
