#!/bin/bash
#
## This script is used to install the necessary packages for the
## development environment.

set -euo pipefail
set -x

THIS_DIR=$(cd "$(dirname "$0")" && pwd)
PACK_DIR=$THIS_DIR/src
mkdir -vp "$PACK_DIR"

CD_OR_DIE() {
	cd "${PACK_DIR}/${1:-}" || exit 1
}

# git submodule update --init --recursive

## HTSlib
## Requirements
# https://github.com/samtools/htslib/blob/develop/INSTALL
# zlib (required)
# libbz2 (required, unless configured with --disable-bz2)
# liblzma (required, unless configured with --disable-lzma)
# libcurl (optional, but strongly recommended)
# libcrypto (optional for Amazon S3 support; not needed on MacOS)
# libdeflate (optional, but strongly recommended for faster gzip)

__htslib() {
	SOURCE_DIR=${1:-htslib}

	CD_OR_DIE "$SOURCE_DIR"
	autoreconf -i
}

__subread() {
	SOURCE_DIR=${1:-subread}
	BUILD_DIR=$SOURCE_DIR/source

	CD_OR_DIE "$BUILD_DIR"

	# Build subread on macOS or Linux
	if [[ $(uname) == Darwin ]]; then
		make -f Makefile.MacOS
	else
		make -f Makefile.Linux
	fi
}

# https://stackoverflow.com/a/16159057
"$@"

# :vim :ft=sh
