[project]
name = "cbmf"
version = "0.1.0"
description = "Combinatorial Bioinformatics Meta-Framework"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["boto3", "paramiko"]

[project.scripts]
cbmf = "cbmf.cli:main"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
