[project]
name = "cbmf"
version = "0.1.0"
description = "Cloud Bioinformatics Management Framework"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = ["boto3"]

[project.scripts]
ec2manager = "ec2manager.cli:main"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
