#!/bin/bash
#
## Install AWS CLI v2
## https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip 
sudo ./aws/install

# clean up
rm -rf awscliv2.zip

# 

# add completion to your shell
# on macOS, add the following to your .zshrc:
# autoload bashcompinit && bashcompinit
# autoload -Uz compinit && compinit
complete -C '/usr/local/bin/aws_completer' aws

# configure credentials; use the ones from the IAM user you created
aws configure
# AWS Access Key ID [None]: <YOUR_ACCESS_KEY_ID>
# AWS Secret Access Key [None]: <YOUR_SECRET_ACCESS_KEY>
# Default region name [None]: us-east-1
# Default output format [None]: [json|text|table]
