#!/bin/bash

align_PE_reads() {
	local aligner="$1" r1_fastq="$2" r2_fastq="$3" reference="$4"
	local align_opts="-p $(nproc) --mm -1 $r1_fastq -2 $r2_fastq -x $reference"
	case "$aligner" in
		hisat2) hisat2 "$align_opts" ;;
		bowtie2) bowtie2 "$align_opts" --dta ;;
		*) err_exit "Invalid aligner: $aligner" ;;
	esac
}

