#!/usr/bin/env python

import sys
import os
import re
import argparse

## argparser for custome arguments (for a more interactive command line UI)

# parser sets species to human or mouse
parser = argparse.ArgumentParser(description='This script will parse arguments for the user')
parser.add_argument('-s', '--species', help='Species to be used for analysis', required=True)
args = parser.parse_args()

# species can only be human or mouse
if args.species != 'human' and args.species != 'mouse':
    print('Species must be human or mouse')
    sys.exit()


