#!/bin/bash
files=(
	CBP_CCS_4_R1.fastq.gz
	CBP_DMSO_4_R1.fastq.gz
	CBP_RUX_4_R1.fastq.gz
	CBP_RUX+CCS_4_R1.fastq.gz
	H3K27ac_CCS_4_R1.fastq.gz
	H3K27ac_DMSO_4_R1.fastq.gz
	H3K27ac_RUX_4_R1.fastq.gz
	H3K27ac_RUX+CCS_4_R1.fastq.gz
	P300_CCS_4_R1.fastq.gz
	P300_DMSO_4_R1.fastq.gz
	P300_RUX_4_R1.fastq.gz
	P300_RUX+CCS_4_R1.fastq.gz
	STAT5_CCS_4_R1.fastq.gz
	STAT5_DMSO_4_R1.fastq.gz
	STAT5_RUX_4_R1.fastq.gz
	STAT5_RUX+CCS_4_R1.fastq.gz
	CBP_CCS_5_R1.fastq.gz
	CBP_DMSO_5_R1.fastq.gz
	CBP_RUX_5_R1.fastq.gz
	CBP_RUX+CCS_5_R1.fastq.gz
	H3K27ac_CCS_5_R1.fastq.gz
	H3K27ac_DMSO_5_R1.fastq.gz
	H3K27ac_RUX_5_R1.fastq.gz
	H3K27ac_RUX+CCS_5_R1.fastq.gz
	P300_CCS_5_R1.fastq.gz
	P300_DMSO_5_R1.fastq.gz
	P300_RUX_5_R1.fastq.gz
	P300_RUX+CCS_5_R1.fastq.gz
	STAT5_CCS_5_R1.fastq.gz
	STAT5_DMSO_5_R1.fastq.gz
	STAT5_RUX_5_R1.fastq.gz
	STAT5_RUX+CCS_5_R1.fastq.gz
)

INPUTS=(
input_CBP_1a_R1.fastq.gz
input_CBP_1a_R2.fastq.gz
input_CBP_1b_R1.fastq.gz
input_CBP_1b_R2.fastq.gz
input_DMSO_1a_R1.fastq.gz
input_DMSO_1a_R2.fastq.gz
input_DMSO_1b_R1.fastq.gz
input_DMSO_1b_R2.fastq.gz
input_RUX_1a_R1.fastq.gz
input_RUX_1a_R2.fastq.gz
input_RUX_1b_R1.fastq.gz
input_RUX_1b_R2.fastq.gz
input_CBP_2_R1.fastq.gz
input_CBP_2_R2.fastq.gz
input_DMSO_2_R1.fastq.gz
input_DMSO_2_R2.fastq.gz
input_RUX_2_R1.fastq.gz
input_RUX_2_R2.fastq.gz
input_RUX+CBP_2_R1.fastq.gz
input_RUX+CBP_2_R2.fastq.gz
)

S3_URI=~/s3/ChIPseq/kalay/fastq

for file in "${files[@]}"; do
	echo "Downloading $file"
	# aws  s3 cp "$S3_URI/$file" . &
	# aws  s3 cp "$S3_URI/${file/_R1.fastq.gz/_R2.fastq.gz}" . &
	# test the mount at 
	cp "$S3_URI/$file" . &
done
echo "Waiting for all downloads to finish"

wait

echo "All files downloaded to $(pwd)"

echo "downloading input files"
for file in "${INPUTS[@]}"; do
	echo "Downloading $file"
	# aws  s3 cp "$S3_URI/$file" . &
	cp "$S3_URI/$file" . &
done
echo "Waiting for all downloads to finish"

wait

echo "All files downloaded to $(pwd)"

