[[software]]
name = "SAMtools"
repository = "https://github.com/samtools/samtools"
publication_name = "Twelve years of SAMtools and BCFtools"
doi = "https://doi.org/10.1093/gigascience/giab008"
version = "samtools 1.20-3-gedf2131 (htslib 1.20-1-gdeeb9f01)"


[[software]]
name = "DROMPAplus"
repository = "https://github.com/rnakato/DROMPAplus"
publication_name = "DROMPA: easy-to-handle peak calling and visualization software for the computational analysis and validation of ChIP-seq data"
doi = "https://doi.org/10.1111/gtc.12058"
version = "N/A"

[[software]]
name = "FastQC"
repository = "https://github.com/s-andrews/FastQC"
publication_name = "FastQC: A Quality Control tool for High Throughput Sequence Data"
doi = "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/"
version = "0.12.0"

[[software]]
name = "bcl2fastq"
repository = "N/A"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

[[software]]
name = "bowtie2"
repository = "https://github.com/BenLangmead/bowtie2"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

[[software]]
name = "cufflinks"
repository = "https://github.com/cole-trapnell-lab/cufflinks"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

[[software]]
name = "ngs"
repository = "N/A"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

[[software]]
name = "STAR"
repository = "https://github.com/alexdobin/STAR"
publication_name = "STAR: ultrafast universal RNA-seq aligner"
doi = "https://doi.org/10.1093/bioinformatics/bts635"
version = "2.7.11b"

[[software]]
name = "stringtie"
repository = "N/A"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

[[software]]
name = "zlib"
repository = "N/A"
publication_name = "N/A"
doi = "N/A"
version = "N/A"

